// AUTO-GENERATED by scripts/build_real_cases.py — real DeepSeek runs as console CONV blocks.
window.DRIP_REAL_CASES = {
 "real-cross-platform-triage": {
  "real": true,
  "title": {
   "zh": "跨平台体检与预算重分配",
   "en": "Cross-platform triage & reallocation"
  },
  "sub": {
   "zh": "7 campaign · Meta/TikTok/腾讯/巨量/快手",
   "en": "7 campaigns · Meta/TikTok/Tencent/OE/KS"
  },
  "q": {
   "zh": "我有跨 Meta/TikTok/腾讯/巨量/快手的多条 campaign，今天预算 $1,400，帮我体检一遍、决定每条放量还是止损、并把预算重分到赢家。",
   "en": "I have campaigns across Meta/TikTok/Tencent/OceanEngine/Kuaishou, $1,400 today — triage them, decide scale vs stop-loss, and reallocate to winners."
  },
  "blocks": [
   {
    "t": "intro",
    "h": "Pause Meta_Broad_v1 and Tiktok_Broad_v1 immediately—CPP is $40 (vs. $16.67 on prospecting) and ROAS just 1.40x. All five prospecting campaigns (Meta, Tiktok, Tencent, OceanEngine, Kuaishou) delivered a 3.80x ROAS with CPP $16.67 yesterday. Scale each of them +10% to $220/day today. Total spend was $1,480 with no anomalies."
   },
   {
    "t": "cot",
    "title": {
     "zh": "Drip 怎么跑的",
     "en": "How Drip ran it"
    },
    "steps": [
     "采集 — 从 5 个平台拉取 7 条 campaign，归一到 AdMetrics。",
     "诊断 — Pause Meta_Broad_v1 and Tiktok_Broad_v1 immediately—CPP is $40 (vs. $16.67 on prospecting) and ROAS just 1.40x. All five prospecting campaigns (Meta, Tiktok, Tencent, OceanEngine, Kuaishou) delivered a 3.80x ROAS with CPP $16.67 yesterday. Scale each of them +10% to $220/day today. Total spend was $1,480 with no anomalies.",
     "策略 — 排出赢家方向，给出下一个创意测试。",
     "创意 — 为赢家方向产出 3 个变体。",
     "分配 — 在 $1,400 总预算内重分：5 放量 / 2 止损。",
     "反馈 — 萃取赢点，回灌下一轮。"
    ]
   },
   {
    "t": "card",
    "act": "scale",
    "actLabel": "SCALE",
    "name": "Meta_Prospecting_v3",
    "plat": "",
    "budget": "$200 → $280",
    "conf": "medium",
    "confLabel": "MEDIUM",
    "why": "The decision to scale by just 10% is correct because while nearly all performance signals are firmly green—CPP is 33% below target, ROAS is 3.8x against a 3.0x goal, and budget headroom sits at 86%—the 12 purchases are still a thin sample, limiting our confidence in the stability of those strong metrics. By only moving to $220/day, we prudently begin to feed more volume into a clearly efficient campaign without risking a sudden efficiency drop from overscaling before the sample size matures.",
    "sigLab": "8 signals 7/8",
    "sigs": [
     [
      "CPP",
      "g",
      "$16.67"
     ],
     [
      "ROAS",
      "g",
      "3.8x"
     ],
     [
      "Purchase CVR",
      "g",
      "0.86%"
     ],
     [
      "Daily Spend",
      "g",
      "$200"
     ]
    ]
   },
   {
    "t": "card",
    "act": "pause",
    "actLabel": "PAUSE",
    "name": "Meta_Broad_v1",
    "plat": "",
    "budget": "$240 → $0",
    "conf": "low",
    "confLabel": "LOW",
    "why": "The campaign's unit economics are broken with a $40 cost per purchase running 60% above target and a 1.4x ROAS far below the 3.0x target, meaning every dollar spent is clearly unprofitable. With only 6 purchases on a thin sample below the 10-purchase minimum, there isn't enough data to justify letting it continue and hope for improvement, so pausing protects the budget until performance can be retested.",
    "sigLab": "8 signals 4/8",
    "sigs": [
     [
      "CPP",
      "r",
      "$40.00"
     ],
     [
      "ROAS",
      "r",
      "1.4x"
     ],
     [
      "Purchase CVR",
      "g",
      "0.75%"
     ],
     [
      "Daily Spend",
      "g",
      "$240"
     ]
    ]
   },
   {
    "t": "kpis",
    "head": {
     "zh": "跨平台再分配",
     "en": "Cross-platform reallocation"
    },
    "sub": {
     "zh": "$1,400 总预算",
     "en": "$1,400 budget"
    },
    "items": [
     {
      "k": {
       "zh": "放量",
       "en": "Scale"
      },
      "v": "5",
      "d": {
       "zh": "条 campaign",
       "en": "campaigns"
      },
      "dc": "up"
     },
     {
      "k": {
       "zh": "止损",
       "en": "Stop-loss"
      },
      "v": "2",
      "d": {
       "zh": "归零",
       "en": "→ $0"
      },
      "dc": "down"
     },
     {
      "k": {
       "zh": "赢家单条",
       "en": "Per winner"
      },
      "v": "$280",
      "d": {
       "zh": "↑ 加投",
       "en": "↑ scaled"
      },
      "dc": "up"
     },
     {
      "k": {
       "zh": "口径",
       "en": "Basis"
      },
      "v": "8/8",
      "d": {
       "zh": "信号 + 规则",
       "en": "signals + rules"
      },
      "dc": "flat"
     }
    ]
   },
   {
    "t": "narr",
    "h": "<strong>Feedback:</strong> tencent outperforms meta on ROAS (3.80x vs 2.60x) — shift weight toward tencent；5 campaigns beat 3x ROAS; their avg CTR 1.40% is the bar for the next creatives"
   }
  ]
 },
 "real-intraday-guard": {
  "real": true,
  "title": {
   "zh": "盘中超支止血",
   "en": "Intraday overspend guard"
  },
  "sub": {
   "zh": "小时级 · pacing / 成本突刺 / 防超投",
   "en": "hourly · pacing / cost-spike / anti-overspend"
  },
  "q": {
   "zh": "盘中帮我盯着花费侧：哪条 pacing 过快、成本突刺或要超投，在预算失控前限速或暂停。",
   "en": "Watch the spend side intraday: which campaigns are pacing too fast, spiking, or about to overspend — throttle or pause before the budget runs away."
  },
  "blocks": [
   {
    "t": "intro",
    "h": "3 条触发限速/暂停，其余 HOLD。"
   },
   {
    "t": "cot",
    "title": {
     "zh": "盘中规则链",
     "en": "Intraday rule chain"
    },
    "steps": [
     "Meta_Prospecting_v3 · pace 1.00× · cost 0.72× target · spike 1.00× · exhausts at 100% of day → HOLD",
     "Meta_Broad_v1 · pace 1.25× · cost 1.76× target · spike 1.69× · exhausts at 80% of day → THROTTLE",
     "Meta_Lookalike_v2 · pace 1.67× · cost 1.08× target · spike 1.04× · exhausts at 60% of day → THROTTLE",
     "Meta_Retarget_v4 · pace 0.50× · cost 0.60× target · spike 0.94× · exhausts at 100% of day → RAISE"
    ]
   },
   {
    "t": "kpis",
    "head": {
     "zh": "盘中花费侧守卫",
     "en": "Intraday spend guard"
    },
    "sub": {
     "zh": "小时级",
     "en": "hourly"
    },
    "items": [
     {
      "k": {
       "zh": "触发动作",
       "en": "Acted"
      },
      "v": "3",
      "d": {
       "zh": "限速/暂停",
       "en": "throttle/pause"
      },
      "dc": "down"
     },
     {
      "k": {
       "zh": "观察",
       "en": "Hold"
      },
      "v": "1",
      "d": {
       "zh": "正常",
       "en": "normal"
      },
      "dc": "flat"
     },
     {
      "k": {
       "zh": "层级",
       "en": "Layer"
      },
      "v": {
       "zh": "花费侧",
       "en": "spend-side"
      },
      "d": {
       "zh": "非 ROI",
       "en": "not ROI"
      },
      "dc": "flat"
     },
     {
      "k": {
       "zh": "护栏",
       "en": "Gate"
      },
      "v": {
       "zh": "已审计",
       "en": "audited"
      },
      "d": {
       "zh": "shadow",
       "en": "shadow"
      },
      "dc": "flat"
     }
    ]
   },
   {
    "t": "card",
    "act": "hold",
    "actLabel": "THROTTLE",
    "name": "Meta_Broad_v1",
    "plat": "meta",
    "budget": "THROTTLE · $240 → $168/day (-30%)",
    "conf": "med",
    "confLabel": {
     "zh": "盘中",
     "en": "intraday"
    },
    "why": "THROTTLE · $240 → $168/day (-30%)",
    "sigLab": "pace 1.25× · cost 1.76× target · spike 1.69× · exhausts at 80% of day",
    "sigs": []
   },
   {
    "t": "card",
    "act": "hold",
    "actLabel": "THROTTLE",
    "name": "Meta_Lookalike_v2",
    "plat": "meta",
    "budget": "THROTTLE · $180 → $153/day (-15%)",
    "conf": "med",
    "confLabel": {
     "zh": "盘中",
     "en": "intraday"
    },
    "why": "THROTTLE · $180 → $153/day (-15%)",
    "sigLab": "pace 1.67× · cost 1.08× target · spike 1.04× · exhausts at 60% of day",
    "sigs": []
   }
  ]
 },
 "real-autopilot": {
  "real": true,
  "title": {
   "zh": "自主托管一轮",
   "en": "Autopilot one cycle"
  },
  "sub": {
   "zh": "信号路由 + 熔断器 · 可审计",
   "en": "signal-routed + circuit breaker · auditable"
  },
  "q": {
   "zh": "按信号自主跑一轮：先止血、再放量/换创意/分配，全程有熔断器，数据异常就停手。shadow 先不真写。",
   "en": "Run one autonomous cycle: stop-loss first, then scale/refresh/allocate, behind a circuit breaker that halts on anomalies. Shadow — no real writes yet."
  },
  "blocks": [
   {
    "t": "intro",
    "h": "局面：bleeding。 通过：2/7 暂停，未触发异常阈值。"
   },
   {
    "t": "cot",
    "title": {
     "zh": "信号路由（确定性）",
     "en": "Signal routing (deterministic)"
    },
    "steps": [
     "stop-loss — pause units with broken unit economics before anything else",
     "reallocate — move the freed budget to the survivors, within the daily cap",
     "hold-rest — leave mixed/thin reads untouched until they clear"
    ]
   },
   {
    "t": "kpis",
    "head": {
     "zh": "自主托管（shadow）",
     "en": "Autopilot (shadow)"
    },
    "sub": {
     "zh": "熔断器保护",
     "en": "breaker-protected"
    },
    "items": [
     {
      "k": {
       "zh": "放量",
       "en": "Scale"
      },
      "v": "5",
      "d": {
       "zh": "条",
       "en": "campaigns"
      },
      "dc": "up"
     },
     {
      "k": {
       "zh": "止损",
       "en": "Stop-loss"
      },
      "v": "2",
      "d": {
       "zh": "归零",
       "en": "→ $0"
      },
      "dc": "down"
     },
     {
      "k": {
       "zh": "熔断器",
       "en": "Breaker"
      },
      "v": {
       "zh": "通过",
       "en": "pass"
      },
      "d": {
       "zh": "无异常",
       "en": "no anomaly"
      },
      "dc": "up"
     },
     {
      "k": {
       "zh": "模式",
       "en": "Mode"
      },
      "v": "shadow",
      "d": {
       "zh": "不真写",
       "en": "no real write"
      },
      "dc": "flat"
     }
    ]
   },
   {
    "t": "narr",
    "h": "<strong>Feedback:</strong> tencent outperforms meta on ROAS (3.80x vs 2.60x) — shift weight toward tencent；5 campaigns beat 3x ROAS; their avg CTR 1.40% is the bar for the next creatives"
   }
  ]
 }
};
window.DRIP_REAL_ORDER = ["real-cross-platform-triage", "real-intraday-guard", "real-autopilot"];
